services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - libretranslate
    environment:
      - LIBRETRANSLATE_URL=http://libretranslate:5000/translate

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,es,fr
      - LT_DEBUG=true
